# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.define "client" do |client|
    client.vm.box = "ubuntu/bionic64"

    client.vm.network "private_network", ip: "10.0.3.20"
    client.vm.network "public_network", bridge: "Wi-Fi", ip: "192.168.0.41"
    
    client.vm.provision "shell", path: "script.sh"
    client.vm.provision "shell", path: "asterisk_b.sh"

    client.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

  end
 
  config.vm.define "server" do |server|
    server.vm.box = "ubuntu/bionic64"
    
    server.vm.network "private_network", ip: "10.0.3.21"
    server.vm.network "public_network", bridge: "Wi-Fi", ip: "192.168.0.40"


    server.vm.network "forwarded_port", guest: 5001, host: 5001

    server.vm.provision "shell", path: "script.sh"
    server.vm.provision "shell", path: "asterisk_a.sh"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    

  end

end


